# faq_data.py
#This File is for Medical FAQ Dataset
FAQ_DATA = {
    "What are the common symptoms of diabetes?": "Common symptoms include increased thirst, frequent urination, fatigue, and blurred vision.",
    "What is a heart attack?": "A heart attack occurs when blood flow to the heart is blocked, causing damage to the heart muscle.",
    "How can I prevent anemia?": "Eat iron-rich foods like leafy greens, beans, red meat, and take iron supplements if prescribed.",
    "What is asthma?": "Asthma is a chronic condition where the airways narrow and swell, causing difficulty in breathing.",
    "How is cholesterol measured?": "Cholesterol is measured using a blood test, checking LDL, HDL, and triglyceride levels.",
    "What are the causes of kidney stones?": "Kidney stones are caused by buildup of minerals and salts in the kidneys, often from dehydration or diet.",
    "What is osteoporosis?": "Osteoporosis is a condition that weakens bones, making them fragile and more likely to break.",
    "How can I improve digestion?": "Eat fiber-rich foods, stay hydrated, exercise regularly, and avoid excessive processed foods.",
    "What is the normal blood pressure range?": "Normal blood pressure is around 120/80 mmHg.",
    "How can I reduce stress naturally?": "Practice meditation, deep breathing, exercise, and maintain a balanced lifestyle.",
    "What is an ulcer?": "An ulcer is a sore on the lining of the stomach or intestine, often caused by infection or medication.",
    "What is insomnia?": "Insomnia is difficulty falling asleep or staying asleep, leading to poor quality of rest.",
    "How can I boost my immunity?": "Eat a balanced diet, exercise regularly, get enough sleep, and manage stress.",
    "What is anemia?": "Anemia is a condition where you lack enough healthy red blood cells to carry oxygen to the body.",
    "What are common symptoms of depression?": "Persistent sadness, loss of interest, fatigue, and difficulty concentrating.",
    "What is migraine?": "A migraine is a severe headache often accompanied by nausea, sensitivity to light, and visual disturbances.",
    "How can I maintain healthy skin?": "Stay hydrated, use sunscreen, eat nutritious foods, and maintain a skincare routine.",
    "What is arthritis?": "Arthritis is inflammation of the joints, causing pain and stiffness.",
    "How do vaccines work?": "Vaccines stimulate the immune system to recognize and fight infections without causing the disease.",
    "What is the difference between viral and bacterial infection?": "Viral infections are caused by viruses and often resolve on their own, while bacterial infections are caused by bacteria and may require antibiotics.",
    "How can I improve heart health?": "Exercise regularly, eat a heart-healthy diet, avoid smoking, and manage stress.",
    "What is a stroke?": "A stroke occurs when blood flow to the brain is interrupted, causing brain cell damage.",
    "How can I manage diabetes?": "Monitor blood sugar, follow a healthy diet, exercise regularly, and take prescribed medications.",
    "What is eczema?": "Eczema is a skin condition causing red, itchy, and inflamed patches.",
    "How can I prevent flu?": "Get an annual flu vaccine, wash hands frequently, and avoid close contact with sick people.",
    "What is a hernia?": "A hernia is when an organ or tissue pushes through a weak spot in the surrounding muscle or tissue wall.",
    "What is gout?": "Gout is a form of arthritis caused by excess uric acid, leading to painful joint inflammation.",
    "How can I maintain healthy bones?": "Consume calcium and vitamin D, exercise regularly, and avoid smoking.",
    "What is the recommended water intake?": "Generally, about 2–3 liters (8–12 cups) per day depending on age, activity, and climate.",
    "What is fibromyalgia?": "Fibromyalgia is a chronic condition causing widespread pain, fatigue, and sleep problems.",
    "What is anemia due to vitamin B12 deficiency?": "It is a type of anemia caused by insufficient vitamin B12, leading to fatigue and nerve problems.",
    "How can I reduce cholesterol naturally?": "Eat fiber-rich foods, reduce saturated fats, exercise, and avoid smoking.",
    "What is thyroid disorder?": "Thyroid disorder occurs when the thyroid gland produces too much or too little hormone, affecting metabolism.",
    "How can I prevent obesity?": "Maintain a balanced diet, exercise regularly, and monitor calorie intake.",
    "What is the difference between type 1 and type 2 diabetes?": "Type 1 is autoimmune and usually starts in childhood, Type 2 is related to lifestyle and insulin resistance.",
    "How can I manage high blood pressure?": "Eat a low-sodium diet, exercise, avoid alcohol and tobacco, and take prescribed medication.",
    "What is bronchitis?": "Bronchitis is inflammation of the bronchial tubes, causing cough and mucus production.",
    "How can I prevent heart disease?": "Eat a balanced diet, exercise, avoid smoking, maintain healthy weight, and control blood pressure.",
    "What is anaphylaxis?": "Anaphylaxis is a severe allergic reaction that can be life-threatening and requires immediate medical attention.",
    "What is a concussion?": "A concussion is a mild traumatic brain injury caused by a blow to the head.",
    "How can I p+revent dehydration?": "Drink sufficient water, avoid excessive alcohol, and monitor fluid loss during exercise.",
    "What is IBS (Irritable Bowel Syndrome)?": "IBS is a digestive disorder causing abdominal pain, bloating, and changes in bowel habits.",
    "What is eczema?": "A condition that makes your skin red, inflamed, and itchy.",
    "How can I maintain mental health?": "Practice mindfulness, maintain social connections, exercise, and get adequate sleep.",
    "What is a cataract?": "A cataract is clouding of the eye's lens, leading to blurred vision.",
    "What is glaucoma?": "Glaucoma is a condition that damages the optic nerve, often due to high eye pressure.",
    "How can I prevent infections?": "Wash hands frequently, maintain hygiene, get vaccinated, and avoid contact with sick individuals.",
    "What is a migraine?": "A migraine is a recurring headache that can be severe, often accompanied by nausea and sensitivity to light.",
    "What is pneumonia?": "Pneumonia is an infection that inflames the air sacs in one or both lungs.",
    "What are antioxidants?": "Antioxidants are substances that protect your cells from damage caused by free radicals.",
    "How can I improve sleep quality?": "Maintain a regular sleep schedule, reduce screen time, avoid caffeine late in the day, and create a comfortable sleep environment.",
    "What is appendicitis?": "Appendicitis is inflammation of the appendix, often requiring surgical removal.",
    "What is hypertension?": "Hypertension is high blood pressure, a condition where the force of blood against your artery walls is too high."
    
}
